/**
 * Phase 1 暗唱100フレーズ — 語感リセット訓練
 *
 * 使い方：
 *   このファイルは curriculum.js の sentenceBank に追記する形で使う。
 *   各フレーズは既存の sentence() ヘルパー関数と同じ形式で定義されている。
 *
 * カテゴリー構成：
 *   cat1: 反応・相槌       (20句) - p1-react-001 〜 020
 *   cat2: 自分のことを話す (20句) - p1-self-001 〜 020
 *   cat3: 理由・説明       (15句) - p1-reason-001 〜 015
 *   cat4: 依頼・確認       (15句) - p1-request-001 〜 015
 *   cat5: 感情・状況       (15句) - p1-emotion-001 〜 015
 *   cat6: つなぎ言葉       (15句) - p1-filler-001 〜 015
 */

(function (root, factory) {
  const data = factory();
  if (typeof module !== "undefined" && module.exports) {
    module.exports = data;
  }
  root.Phase1Phrases = data;
})(typeof globalThis !== "undefined" ? globalThis : window, function () {

  // ─────────────────────────────────────────────
  // カテゴリー1：反応・相槌（20句）
  // 最優先で覚える。会話が途切れない救命稻草。
  // ─────────────────────────────────────────────
  const cat1_reaction = [
    {
      id: "p1-react-001",
      category: "反応・相槌",
      priority: 1,
      ja: "そうですか。",
      kana: "そうですか。",
      zh: "是这样吗。（中性回应）",
      scene: "对方说了某件事，你需要回应时",
      pattern: "相槌・中立",
      week: 1,
    },
    {
      id: "p1-react-002",
      category: "反応・相槌",
      priority: 1,
      ja: "なるほど。",
      kana: "なるほど。",
      zh: "原来如此。",
      scene: "理解了对方说的内容时",
      pattern: "相槌・理解",
      week: 1,
    },
    {
      id: "p1-react-003",
      category: "反応・相槌",
      priority: 1,
      ja: "そうなんですか！",
      kana: "そうなんですか！",
      zh: "真的吗！（带惊讶）",
      scene: "听到意外信息时",
      pattern: "相槌・驚き",
      week: 1,
    },
    {
      id: "p1-react-004",
      category: "反応・相槌",
      priority: 1,
      ja: "えっ、本当ですか？",
      kana: "えっ、ほんとうですか？",
      zh: "诶，真的吗？",
      scene: "听到令人意外的消息时",
      pattern: "相槌・驚き",
      week: 1,
    },
    {
      id: "p1-react-005",
      category: "反応・相槌",
      priority: 1,
      ja: "それはよかったですね。",
      kana: "それはよかったですね。",
      zh: "那太好了。",
      scene: "对方分享好消息时",
      pattern: "相槌・共感（嬉しい）",
      week: 1,
    },
    {
      id: "p1-react-006",
      category: "反応・相槌",
      priority: 1,
      ja: "それは大変でしたね。",
      kana: "それはたいへんでしたね。",
      zh: "那真是辛苦了。",
      scene: "对方分享困难经历时",
      pattern: "相槌・共感（辛い）",
      week: 1,
    },
    {
      id: "p1-react-007",
      category: "反応・相槌",
      priority: 1,
      ja: "たしかに。",
      kana: "たしかに。",
      zh: "确实。",
      scene: "认同对方的说法时",
      pattern: "相槌・同意",
      week: 1,
    },
    {
      id: "p1-react-008",
      category: "反応・相槌",
      priority: 1,
      ja: "おっしゃる通りです。",
      kana: "おっしゃるとおりです。",
      zh: "正如您所说。（敬语）",
      scene: "正式场合完全同意对方时",
      pattern: "相槌・同意（敬語）",
      week: 2,
    },
    {
      id: "p1-react-009",
      category: "反応・相槌",
      priority: 1,
      ja: "私もそう思います。",
      kana: "わたしもそうおもいます。",
      zh: "我也这么认为。",
      scene: "表示自己与对方意见一致时",
      pattern: "相槌・同意",
      week: 1,
    },
    {
      id: "p1-react-010",
      category: "反応・相槌",
      priority: 2,
      ja: "そうかもしれませんね。",
      kana: "そうかもしれませんね。",
      zh: "也许是这样呢。",
      scene: "不完全确定但倾向同意时",
      pattern: "相槌・曖昧同意",
      week: 2,
    },
    {
      id: "p1-react-011",
      category: "反応・相槌",
      priority: 1,
      ja: "ちょっと待ってください。",
      kana: "ちょっとまってください。",
      zh: "请稍等一下。",
      scene: "需要对方等待时",
      pattern: "時間稼ぎ",
      week: 1,
    },
    {
      id: "p1-react-012",
      category: "反応・相槌",
      priority: 1,
      ja: "もう一度言っていただけますか？",
      kana: "もういちどいっていただけますか？",
      zh: "可以再说一次吗？",
      scene: "没听清楚时",
      pattern: "確認・聞き直し",
      week: 1,
    },
    {
      id: "p1-react-013",
      category: "反応・相槌",
      priority: 1,
      ja: "どういう意味ですか？",
      kana: "どういういみですか？",
      zh: "是什么意思？",
      scene: "不理解某个词或说法时",
      pattern: "確認・意味",
      week: 1,
    },
    {
      id: "p1-react-014",
      category: "反応・相槌",
      priority: 1,
      ja: "すみません、よく聞こえませんでした。",
      kana: "すみません、よくきこえませんでした。",
      zh: "不好意思，我没听清楚。",
      scene: "声音太小或嘈杂没听清时",
      pattern: "確認・聞き直し",
      week: 1,
    },
    {
      id: "p1-react-015",
      category: "反応・相槌",
      priority: 1,
      ja: "ああ、なるほど、わかりました。",
      kana: "ああ、なるほど、わかりました。",
      zh: "啊，原来如此，我明白了。",
      scene: "经过解释后终于理解时",
      pattern: "理解・納得",
      week: 1,
    },
    {
      id: "p1-react-016",
      category: "反応・相槌",
      priority: 2,
      ja: "それはどういうことですか？",
      kana: "それはどういうことですか？",
      zh: "那是怎么回事？",
      scene: "需要对方进一步解释时",
      pattern: "確認・詳細",
      week: 2,
    },
    {
      id: "p1-react-017",
      category: "反応・相槌",
      priority: 2,
      ja: "面白いですね。",
      kana: "おもしろいですね。",
      zh: "很有意思呢。",
      scene: "对方说了有趣的事时",
      pattern: "相槌・興味",
      week: 2,
    },
    {
      id: "p1-react-018",
      category: "反応・相槌",
      priority: 2,
      ja: "難しいですね。",
      kana: "むずかしいですね。",
      zh: "真难呢。",
      scene: "谈论困难话题时",
      pattern: "相槌・困難",
      week: 2,
    },
    {
      id: "p1-react-019",
      category: "反応・相槌",
      priority: 1,
      ja: "いいですね！",
      kana: "いいですね！",
      zh: "好啊！/ 不错！",
      scene: "表示赞同或称赞时",
      pattern: "相槌・肯定",
      week: 1,
    },
    {
      id: "p1-react-020",
      category: "反応・相槌",
      priority: 2,
      ja: "そうですよね。",
      kana: "そうですよね。",
      zh: "对吧，是这样的。",
      scene: "寻求对方认同或自己认同时",
      pattern: "相槌・共感",
      week: 2,
    },
  ];

  // ─────────────────────────────────────────────
  // カテゴリー2：自分のことを話す（20句）
  // 面接の基礎。自己PRに直結。
  // ─────────────────────────────────────────────
  const cat2_self = [
    {
      id: "p1-self-001",
      category: "自分のことを話す",
      priority: 1,
      ja: "私は〔名前〕と申します。",
      kana: "わたしは〔なまえ〕ともうします。",
      zh: "我叫〔名字〕。（正式自我介绍）",
      scene: "正式场合自我介绍",
      pattern: "自己紹介・敬語",
      week: 1,
      fillIn: "〔名前〕",
    },
    {
      id: "p1-self-002",
      category: "自分のことを話す",
      priority: 1,
      ja: "〔都市〕に住んでいます。",
      kana: "〔としめい〕にすんでいます。",
      zh: "我住在〔城市〕。",
      scene: "说明居住地",
      pattern: "居住・に住む",
      week: 1,
      fillIn: "〔都市〕",
    },
    {
      id: "p1-self-003",
      category: "自分のことを話す",
      priority: 1,
      ja: "〔職業・仕事〕をしています。",
      kana: "〔しごと〕をしています。",
      zh: "我做〔工作〕。",
      scene: "介绍职业",
      pattern: "職業・をしています",
      week: 1,
      fillIn: "〔職業〕",
    },
    {
      id: "p1-self-004",
      category: "自分のことを話す",
      priority: 1,
      ja: "趣味は〔趣味〕です。",
      kana: "しゅみは〔しゅみ〕です。",
      zh: "我的爱好是〔爱好〕。",
      scene: "介绍兴趣爱好",
      pattern: "趣味・は〜です",
      week: 1,
      fillIn: "〔趣味〕",
    },
    {
      id: "p1-self-005",
      category: "自分のことを話す",
      priority: 2,
      ja: "最近、〔テーマ〕に興味があります。",
      kana: "さいきん、〔てーま〕にきょうみがあります。",
      zh: "最近对〔某事〕很感兴趣。",
      scene: "谈论近期关注的事",
      pattern: "興味・に興味があります",
      week: 2,
      fillIn: "〔テーマ〕",
    },
    {
      id: "p1-self-006",
      category: "自分のことを話す",
      priority: 1,
      ja: "〔もの・こと〕が好きです。特に〔具体例〕が。",
      kana: "〔もの〕がすきです。とくに〔ぐたいれい〕が。",
      zh: "我喜欢〔事物〕。尤其是〔具体〕。",
      scene: "描述自己的喜好",
      pattern: "好き・特に",
      week: 1,
      fillIn: "〔もの〕・〔具体例〕",
    },
    {
      id: "p1-self-007",
      category: "自分のことを話す",
      priority: 2,
      ja: "〔こと〕はあまり得意ではありません。",
      kana: "〔こと〕はあまりとくいではありません。",
      zh: "〔某事〕不太擅长。",
      scene: "诚实说明弱点",
      pattern: "弱点・得意ではない",
      week: 2,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-self-008",
      category: "自分のことを話す",
      priority: 1,
      ja: "〔こと〕を大切にしています。",
      kana: "〔こと〕をたいせつにしています。",
      zh: "我很重视〔某事〕。",
      scene: "说明自己的价值观",
      pattern: "価値観・大切にする",
      week: 2,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-self-009",
      category: "自分のことを話す",
      priority: 2,
      ja: "子供の頃は〔状況〕でした。",
      kana: "こどものころは〔じょうきょう〕でした。",
      zh: "小时候〔是什么状况〕。",
      scene: "谈论童年经历",
      pattern: "過去・子供の頃",
      week: 3,
      fillIn: "〔状況〕",
    },
    {
      id: "p1-self-010",
      category: "自分のことを話す",
      priority: 1,
      ja: "〔経験〕をしたことがあります。",
      kana: "〔けいけん〕をしたことがあります。",
      zh: "我有过〔经历〕的经验。",
      scene: "说明自己的经验",
      pattern: "経験・たことがある",
      week: 2,
      fillIn: "〔経験〕",
    },
    {
      id: "p1-self-011",
      category: "自分のことを話す",
      priority: 2,
      ja: "〔場面〕のとき、〔感情〕と感じました。",
      kana: "〔ばめん〕のとき、〔かんじょう〕とかんじました。",
      zh: "在〔场景〕时，感到〔情感〕。",
      scene: "描述经历中的感受",
      pattern: "感情・ときに感じる",
      week: 3,
      fillIn: "〔場面〕・〔感情〕",
    },
    {
      id: "p1-self-012",
      category: "自分のことを話す",
      priority: 2,
      ja: "私の夢は〔夢〕です。",
      kana: "わたしのゆめは〔ゆめ〕です。",
      zh: "我的梦想是〔梦想〕。",
      scene: "谈论自己的目标",
      pattern: "夢・目標",
      week: 3,
      fillIn: "〔夢〕",
    },
    {
      id: "p1-self-013",
      category: "自分のことを話す",
      priority: 1,
      ja: "将来的には〔こと〕したいと思っています。",
      kana: "しょうらいてきには〔こと〕したいとおもっています。",
      zh: "将来的话，想〔做某事〕。",
      scene: "谈论未来计划",
      pattern: "将来・たいと思っています",
      week: 3,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-self-014",
      category: "自分のことを話す",
      priority: 2,
      ja: "〔こと〕を続けて〔期間〕になります。",
      kana: "〔こと〕をつづけて〔きかん〕になります。",
      zh: "坚持〔某事〕已经〔时间〕了。",
      scene: "强调持续做某事的时长",
      pattern: "継続・期間",
      week: 3,
      fillIn: "〔こと〕・〔期間〕",
    },
    {
      id: "p1-self-015",
      category: "自分のことを話す",
      priority: 2,
      ja: "私は〔性格〕なタイプだと思います。",
      kana: "わたしは〔せいかく〕なたいぷだとおもいます。",
      zh: "我认为自己是〔性格〕的类型。",
      scene: "描述自己的性格",
      pattern: "性格・タイプ",
      week: 3,
      fillIn: "〔性格〕",
    },
    {
      id: "p1-self-016",
      category: "自分のことを話す",
      priority: 2,
      ja: "よく〔特徴〕と言われます。",
      kana: "よく〔とくちょう〕といわれます。",
      zh: "别人经常说我〔某特点〕。",
      scene: "借他人评价描述自己",
      pattern: "他者評価・言われる",
      week: 4,
      fillIn: "〔特徴〕",
    },
    {
      id: "p1-self-017",
      category: "自分のことを話す",
      priority: 3,
      ja: "最近、〔気づいたこと〕ということに気づきました。",
      kana: "さいきん、〔きづいたこと〕ということにきづきました。",
      zh: "最近，我意识到了〔某事〕。",
      scene: "谈论近期的自我发现",
      pattern: "気づき",
      week: 4,
      fillIn: "〔気づいたこと〕",
    },
    {
      id: "p1-self-018",
      category: "自分のことを話す",
      priority: 2,
      ja: "〔こと〕が課題だと思っています。",
      kana: "〔こと〕がかだいだとおもっています。",
      zh: "我认为〔某事〕是自己的课题。",
      scene: "说明自己的不足和改进点",
      pattern: "課題・自己分析",
      week: 4,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-self-019",
      category: "自分のことを話す",
      priority: 2,
      ja: "〔こと〕という点では自信があります。",
      kana: "〔こと〕というてんではじしんがあります。",
      zh: "在〔某方面〕我有自信。",
      scene: "说明自己的优势",
      pattern: "強み・自信",
      week: 4,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-self-020",
      category: "自分のことを話す",
      priority: 2,
      ja: "もっと〔こと〕できるようになりたいです。",
      kana: "もっと〔こと〕できるようになりたいです。",
      zh: "我想变得更能〔做某事〕。",
      scene: "表达学习和成长意愿",
      pattern: "成長意欲・ようになりたい",
      week: 4,
      fillIn: "〔こと〕",
    },
  ];

  // ─────────────────────────────────────────────
  // カテゴリー3：理由・説明（15句）
  // ─────────────────────────────────────────────
  const cat3_reason = [
    {
      id: "p1-reason-001",
      category: "理由・説明",
      priority: 1,
      ja: "なぜかというと、〔理由〕からです。",
      kana: "なぜかというと、〔りゆう〕からです。",
      zh: "原因是〔理由〕。（因为…）",
      scene: "解释原因时，语气较正式",
      pattern: "理由・なぜかというと",
      week: 3,
      fillIn: "〔理由〕",
    },
    {
      id: "p1-reason-002",
      category: "理由・説明",
      priority: 1,
      ja: "〔理由〕なので、〔結論〕です。",
      kana: "〔りゆう〕なので、〔けつろん〕です。",
      zh: "因为〔理由〕，所以〔结论〕。",
      scene: "日常说明原因",
      pattern: "理由・なので",
      week: 3,
      fillIn: "〔理由〕・〔結論〕",
    },
    {
      id: "p1-reason-003",
      category: "理由・説明",
      priority: 2,
      ja: "〔理由〕という理由で〔行動〕しました。",
      kana: "〔りゆう〕というりゆうで〔こうどう〕しました。",
      zh: "以〔理由〕为由，做了〔行动〕。",
      scene: "解释做某事的理由",
      pattern: "理由・という理由で",
      week: 4,
      fillIn: "〔理由〕・〔行動〕",
    },
    {
      id: "p1-reason-004",
      category: "理由・説明",
      priority: 1,
      ja: "つまり、〔まとめ〕ということです。",
      kana: "つまり、〔まとめ〕ということです。",
      zh: "也就是说，〔总结〕。",
      scene: "总结或重新表达刚才说的话",
      pattern: "まとめ・つまり",
      week: 3,
      fillIn: "〔まとめ〕",
    },
    {
      id: "p1-reason-005",
      category: "理由・説明",
      priority: 1,
      ja: "例えば、〔例〕という場合があります。",
      kana: "たとえば、〔れい〕というばあいがあります。",
      zh: "比如，有〔举例〕这样的情况。",
      scene: "举例说明",
      pattern: "例・例えば",
      week: 3,
      fillIn: "〔例〕",
    },
    {
      id: "p1-reason-006",
      category: "理由・説明",
      priority: 1,
      ja: "具体的には、〔内容〕です。",
      kana: "ぐたいてきには、〔ないよう〕です。",
      zh: "具体来说，是〔内容〕。",
      scene: "提供具体细节",
      pattern: "具体化・具体的には",
      week: 3,
      fillIn: "〔内容〕",
    },
    {
      id: "p1-reason-007",
      category: "理由・説明",
      priority: 2,
      ja: "〔背景〕という背景があります。",
      kana: "〔はいけい〕というはいけいがあります。",
      zh: "有〔背景〕这样的背景。",
      scene: "解释事情的来龙去脉",
      pattern: "背景説明",
      week: 4,
      fillIn: "〔背景〕",
    },
    {
      id: "p1-reason-008",
      category: "理由・説明",
      priority: 2,
      ja: "これは〔原因〕が原因だと思います。",
      kana: "これは〔げんいん〕がげんいんだとおもいます。",
      zh: "我认为这是〔原因〕造成的。",
      scene: "分析问题原因",
      pattern: "原因分析",
      week: 4,
      fillIn: "〔原因〕",
    },
    {
      id: "p1-reason-009",
      category: "理由・説明",
      priority: 2,
      ja: "〔経緯〕の結果として、〔結果〕になりました。",
      kana: "〔けいい〕のけっかとして、〔けっか〕になりました。",
      zh: "作为〔经过〕的结果，变成了〔结果〕。",
      scene: "叙述事情发展结果",
      pattern: "結果・の結果として",
      week: 5,
      fillIn: "〔経緯〕・〔結果〕",
    },
    {
      id: "p1-reason-010",
      category: "理由・説明",
      priority: 2,
      ja: "〔A〕とはいえ、〔B〕という面もあります。",
      kana: "〔A〕とはいえ、〔B〕というめんもあります。",
      zh: "虽说〔A〕，但也有〔B〕的一面。",
      scene: "表达事物的两面性",
      pattern: "逆接・とはいえ",
      week: 5,
      fillIn: "〔A〕・〔B〕",
    },
    {
      id: "p1-reason-011",
      category: "理由・説明",
      priority: 2,
      ja: "一方で、〔別の視点〕という考え方もあります。",
      kana: "いっぽうで、〔べつのしてん〕というかんがえかたもあります。",
      zh: "另一方面，也有〔另一观点〕这种看法。",
      scene: "提出另一个角度",
      pattern: "対比・一方で",
      week: 5,
      fillIn: "〔別の視点〕",
    },
    {
      id: "p1-reason-012",
      category: "理由・説明",
      priority: 2,
      ja: "ただ、〔課題〕という点が課題です。",
      kana: "ただ、〔かだい〕というてんがかだいです。",
      zh: "不过，〔问题点〕是个课题。",
      scene: "指出问题或不足",
      pattern: "問題点・ただ",
      week: 5,
      fillIn: "〔課題〕",
    },
    {
      id: "p1-reason-013",
      category: "理由・説明",
      priority: 3,
      ja: "それによって、〔変化〕が変わりました。",
      kana: "それによって、〔へんか〕がかわりました。",
      zh: "因此，〔某事〕发生了变化。",
      scene: "说明因果关系中的变化",
      pattern: "因果・それによって",
      week: 5,
      fillIn: "〔変化〕",
    },
    {
      id: "p1-reason-014",
      category: "理由・説明",
      priority: 2,
      ja: "〔A〕という点で、〔B〕と似ています。",
      kana: "〔A〕というてんで、〔B〕とにています。",
      zh: "在〔A〕这点上，和〔B〕很相似。",
      scene: "做类比说明",
      pattern: "比較・似ている",
      week: 5,
      fillIn: "〔A〕・〔B〕",
    },
    {
      id: "p1-reason-015",
      category: "理由・説明",
      priority: 2,
      ja: "〔こと〕という意味では、〔判断〕と言えます。",
      kana: "〔こと〕というみでは、〔はんだん〕といえます。",
      zh: "从〔某含义〕的角度来说，可以说是〔判断〕。",
      scene: "从某个角度下结论",
      pattern: "という意味では",
      week: 6,
      fillIn: "〔こと〕・〔判断〕",
    },
  ];

  // ─────────────────────────────────────────────
  // カテゴリー4：依頼・確認・調整（15句）
  // ─────────────────────────────────────────────
  const cat4_request = [
    {
      id: "p1-request-001",
      category: "依頼・確認",
      priority: 1,
      ja: "〔こと〕していただけますか？",
      kana: "〔こと〕していただけますか？",
      zh: "可以请您〔做某事〕吗？（礼貌请求）",
      scene: "礼貌地请求别人帮忙",
      pattern: "依頼・ていただけますか",
      week: 2,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-request-002",
      category: "依頼・確認",
      priority: 1,
      ja: "〔こと〕をお願いできますか？",
      kana: "〔こと〕をおねがいできますか？",
      zh: "可以拜托您〔某事〕吗？",
      scene: "礼貌委托",
      pattern: "依頼・をお願いできますか",
      week: 2,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-request-003",
      category: "依頼・確認",
      priority: 1,
      ja: "〔こと〕について確認させてください。",
      kana: "〔こと〕についてかくにんさせてください。",
      zh: "请允许我确认一下〔某事〕。",
      scene: "礼貌地提出确认请求",
      pattern: "確認・させてください",
      week: 2,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-request-004",
      category: "依頼・確認",
      priority: 1,
      ja: "〔内容〕でよろしいですか？",
      kana: "〔ないよう〕でよろしいですか？",
      zh: "〔内容〕这样可以吗？",
      scene: "确认对方是否同意",
      pattern: "確認・でよろしいですか",
      week: 2,
      fillIn: "〔内容〕",
    },
    {
      id: "p1-request-005",
      category: "依頼・確認",
      priority: 1,
      ja: "〔内容〕という理解で合っていますか？",
      kana: "〔ないよう〕というりかいであっていますか？",
      zh: "我理解成〔内容〕，对吗？",
      scene: "确认自己的理解是否正确",
      pattern: "確認・という理解で",
      week: 3,
      fillIn: "〔内容〕",
    },
    {
      id: "p1-request-006",
      category: "依頼・確認",
      priority: 1,
      ja: "少し時間をいただけますか？",
      kana: "すこしじかんをいただけますか？",
      zh: "可以给我一点时间吗？",
      scene: "需要时间思考时",
      pattern: "時間・いただけますか",
      week: 2,
      fillIn: "",
    },
    {
      id: "p1-request-007",
      category: "依頼・確認",
      priority: 1,
      ja: "もう少し詳しく教えていただけますか？",
      kana: "もうすこしくわしくおしえていただけますか？",
      zh: "可以再详细说明一下吗？",
      scene: "需要更多细节时",
      pattern: "詳細・教えていただけますか",
      week: 2,
      fillIn: "",
    },
    {
      id: "p1-request-008",
      category: "依頼・確認",
      priority: 1,
      ja: "〔こと〕について教えてください。",
      kana: "〔こと〕についておしえてください。",
      zh: "请告诉我关于〔某事〕的信息。",
      scene: "请求对方提供信息",
      pattern: "情報収集・教えてください",
      week: 2,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-request-009",
      category: "依頼・確認",
      priority: 2,
      ja: "ちょっと難しいですが、やってみます。",
      kana: "ちょっとむずかしいですが、やってみます。",
      zh: "有点难，但我试试看。",
      scene: "接受挑战时表示积极",
      pattern: "挑戦・やってみます",
      week: 3,
      fillIn: "",
    },
    {
      id: "p1-request-010",
      category: "依頼・確認",
      priority: 2,
      ja: "〔こと〕は私には少し難しいかもしれません。",
      kana: "〔こと〕はわたしにはすこしむずかしいかもしれません。",
      zh: "〔某事〕对我来说可能有点难。",
      scene: "诚实说明自己的局限",
      pattern: "謙遜・難しいかもしれません",
      week: 3,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-request-011",
      category: "依頼・確認",
      priority: 2,
      ja: "〔こと〕について相談してもいいですか？",
      kana: "〔こと〕についてそうだんしてもいいですか？",
      zh: "关于〔某事〕，可以和您商量吗？",
      scene: "提出商量请求",
      pattern: "相談・てもいいですか",
      week: 3,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-request-012",
      category: "依頼・確認",
      priority: 2,
      ja: "〔こと〕のことが気になっています。",
      kana: "〔こと〕のことがきになっています。",
      zh: "我一直在意〔某事〕。",
      scene: "表达对某事的关注",
      pattern: "気になる",
      week: 4,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-request-013",
      category: "依頼・確認",
      priority: 1,
      ja: "ご迷惑をおかけして申し訳ありません。",
      kana: "ごめいわくをおかけしてもうしわけありません。",
      zh: "给您添麻烦了，非常抱歉。",
      scene: "正式道歉",
      pattern: "謝罪・申し訳ありません",
      week: 2,
      fillIn: "",
    },
    {
      id: "p1-request-014",
      category: "依頼・確認",
      priority: 2,
      ja: "お手数をおかけしますが、〔依頼〕をお願いします。",
      kana: "おてすうをおかけしますが、〔いらい〕をおねがいします。",
      zh: "给您添麻烦了，请帮忙〔某事〕。",
      scene: "在正式请求前表达歉意",
      pattern: "依頼・お手数をおかけしますが",
      week: 4,
      fillIn: "〔依頼〕",
    },
    {
      id: "p1-request-015",
      category: "依頼・確認",
      priority: 1,
      ja: "よろしくお願いいたします。",
      kana: "よろしくおねがいいたします。",
      zh: "请多关照。/ 拜托了。",
      scene: "结束请求、信件结尾、自我介绍后",
      pattern: "定型表現・お願いいたします",
      week: 1,
      fillIn: "",
    },
  ];

  // ─────────────────────────────────────────────
  // カテゴリー5：感情・状況表現（15句）
  // ─────────────────────────────────────────────
  const cat5_emotion = [
    {
      id: "p1-emotion-001",
      category: "感情・状況",
      priority: 1,
      ja: "〔こと〕して、とても嬉しかったです。",
      kana: "〔こと〕して、とてもうれしかったです。",
      zh: "〔某事〕，让我非常高兴。",
      scene: "表达正面情绪",
      pattern: "感情・嬉しかったです",
      week: 3,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-emotion-002",
      category: "感情・状況",
      priority: 2,
      ja: "正直、少し不安でした。",
      kana: "しょうじき、すこしふあんでした。",
      zh: "说实话，我有点不安。",
      scene: "坦诚表达负面情绪",
      pattern: "感情・正直・不安",
      week: 4,
      fillIn: "",
    },
    {
      id: "p1-emotion-003",
      category: "感情・状況",
      priority: 2,
      ja: "最初は戸惑いましたが、〔結果〕でした。",
      kana: "さいしょはとまどいましたが、〔けっか〕でした。",
      zh: "最开始有些困惑，但〔结果〕。",
      scene: "描述从困惑到适应的过程",
      pattern: "感情変化・戸惑い→克服",
      week: 4,
      fillIn: "〔結果〕",
    },
    {
      id: "p1-emotion-004",
      category: "感情・状況",
      priority: 2,
      ja: "だんだん慣れてきました。",
      kana: "だんだんなれてきました。",
      zh: "渐渐习惯了。",
      scene: "说明正在适应新环境",
      pattern: "変化・だんだん慣れる",
      week: 3,
      fillIn: "",
    },
    {
      id: "p1-emotion-005",
      category: "感情・状況",
      priority: 2,
      ja: "思っていたより〔感想〕でした。",
      kana: "おもっていたより〔かんそう〕でした。",
      zh: "比我想象的更〔感受〕。",
      scene: "表达与预期不同的感受",
      pattern: "比較・思っていたより",
      week: 4,
      fillIn: "〔感想〕",
    },
    {
      id: "p1-emotion-006",
      category: "感情・状況",
      priority: 2,
      ja: "意外と〔感想〕でした。",
      kana: "いがいと〔かんそう〕でした。",
      zh: "意外地〔感受〕。",
      scene: "表达意外的感受",
      pattern: "驚き・意外と",
      week: 4,
      fillIn: "〔感想〕",
    },
    {
      id: "p1-emotion-007",
      category: "感情・状況",
      priority: 1,
      ja: "〔場面〕のときは、特にやりがいを感じます。",
      kana: "〔ばめん〕のときは、とくにやりがいをかんじます。",
      zh: "在〔场景〕的时候，特别有成就感。",
      scene: "说明工作或活动中最有意义的时刻",
      pattern: "やりがい",
      week: 3,
      fillIn: "〔場面〕",
    },
    {
      id: "p1-emotion-008",
      category: "感情・状況",
      priority: 2,
      ja: "〔こと〕は少しストレスを感じます。",
      kana: "〔こと〕はすこしすとれすをかんじます。",
      zh: "〔某事〕让我有点有压力。",
      scene: "说明压力来源",
      pattern: "ストレス",
      week: 4,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-emotion-009",
      category: "感情・状況",
      priority: 3,
      ja: "〔こと〕のことで頭がいっぱいです。",
      kana: "〔こと〕のことであたまがいっぱいです。",
      zh: "脑子里全是〔某事〕。",
      scene: "说明非常专注或担心某事",
      pattern: "集中・頭がいっぱい",
      week: 5,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-emotion-010",
      category: "感情・状況",
      priority: 2,
      ja: "〔こと〕について、まだ迷っています。",
      kana: "〔こと〕についてまだまよっています。",
      zh: "关于〔某事〕，还在犹豫中。",
      scene: "表达未做决定的状态",
      pattern: "迷い・まだ〜ています",
      week: 5,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-emotion-011",
      category: "感情・状況",
      priority: 2,
      ja: "〔こと〕できて、よかったと思っています。",
      kana: "〔こと〕できて、よかったとおもっています。",
      zh: "能够〔做到某事〕，我认为很好。",
      scene: "回顾并肯定自己的行动",
      pattern: "振り返り・よかった",
      week: 5,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-emotion-012",
      category: "感情・状況",
      priority: 2,
      ja: "〔体験〕が心に残っています。",
      kana: "〔たいけん〕がこころにのこっています。",
      zh: "〔经历〕深深留在心里。",
      scene: "说明印象深刻的体验",
      pattern: "印象・心に残る",
      week: 5,
      fillIn: "〔体験〕",
    },
    {
      id: "p1-emotion-013",
      category: "感情・状況",
      priority: 2,
      ja: "〔こと〕ということに、改めて気づきました。",
      kana: "〔こと〕ということに、あらためてきづきました。",
      zh: "重新意识到了〔某事〕。",
      scene: "表达重新认识到某事的体悟",
      pattern: "気づき・改めて",
      week: 6,
      fillIn: "〔こと〕",
    },
    {
      id: "p1-emotion-014",
      category: "感情・状況",
      priority: 1,
      ja: "〔人・こと〕のおかげで、〔結果〕できました。",
      kana: "〔ひと〕のおかげで、〔けっか〕できました。",
      zh: "多亏了〔某人/某事〕，才能〔做到〕。",
      scene: "表达感谢，说明成功原因",
      pattern: "感謝・おかげで",
      week: 3,
      fillIn: "〔人・こと〕・〔結果〕",
    },
    {
      id: "p1-emotion-015",
      category: "感情・状況",
      priority: 2,
      ja: "〔こと〕ということを、身をもって学びました。",
      kana: "〔こと〕ということを、みをもってまなびました。",
      zh: "切身体会到了〔某道理〕。",
      scene: "通过亲身经历得出的教训",
      pattern: "学び・身をもって",
      week: 6,
      fillIn: "〔こと〕",
    },
  ];

  // ─────────────────────────────────────────────
  // カテゴリー6：つなぎ言葉（15句）
  // ★最優先★ 沈黙を避ける最大の武器
  // ─────────────────────────────────────────────
  const cat6_filler = [
    {
      id: "p1-filler-001",
      category: "つなぎ言葉",
      priority: 1,
      ja: "えーと、〔内容〕ですね。",
      kana: "えーと、〔ないよう〕ですね。",
      zh: "嗯……是〔内容〕呢。",
      scene: "思考时填补沉默",
      pattern: "間埋め・えーと",
      week: 1,
      fillIn: "〔内容〕",
    },
    {
      id: "p1-filler-002",
      category: "つなぎ言葉",
      priority: 1,
      ja: "そうですね、〔意見〕と思います。",
      kana: "そうですね、〔いけん〕とおもいます。",
      zh: "嗯……我觉得〔意见〕。",
      scene: "边思考边表达意见",
      pattern: "間埋め・そうですね",
      week: 1,
      fillIn: "〔意見〕",
    },
    {
      id: "p1-filler-003",
      category: "つなぎ言葉",
      priority: 1,
      ja: "少し考えさせてください。",
      kana: "すこしかんがえさせてください。",
      zh: "请让我想一下。",
      scene: "需要思考时争取时间",
      pattern: "時間稼ぎ",
      week: 1,
      fillIn: "",
    },
    {
      id: "p1-filler-004",
      category: "つなぎ言葉",
      priority: 1,
      ja: "〔内容〕という感じですかね。",
      kana: "〔ないよう〕というかんじですかね。",
      zh: "大概是〔内容〕那种感觉吧。",
      scene: "不太确定时给出模糊回答",
      pattern: "曖昧・という感じ",
      week: 1,
      fillIn: "〔内容〕",
    },
    {
      id: "p1-filler-005",
      category: "つなぎ言葉",
      priority: 1,
      ja: "〔A〕という部分が大きいと思います。",
      kana: "〔A〕というぶぶんがおおきいとおもいます。",
      zh: "我认为〔A〕这个方面比较大。",
      scene: "强调某个方面的重要性",
      pattern: "強調・という部分",
      week: 2,
      fillIn: "〔A〕",
    },
    {
      id: "p1-filler-006",
      category: "つなぎ言葉",
      priority: 1,
      ja: "それで言うと、〔内容〕ですね。",
      kana: "それでいうと、〔ないよう〕ですね。",
      zh: "从那个角度来说，是〔内容〕。",
      scene: "承接对方话题展开自己的说法",
      pattern: "つなぎ・それで言うと",
      week: 2,
      fillIn: "〔内容〕",
    },
    {
      id: "p1-filler-007",
      category: "つなぎ言葉",
      priority: 1,
      ja: "あとは、〔追加内容〕という点もあります。",
      kana: "あとは、〔ついかないよう〕というてんもあります。",
      zh: "另外，还有〔补充内容〕这一点。",
      scene: "补充说明时",
      pattern: "追加・あとは",
      week: 2,
      fillIn: "〔追加内容〕",
    },
    {
      id: "p1-filler-008",
      category: "つなぎ言葉",
      priority: 2,
      ja: "話が少し戻りますが、〔内容〕。",
      kana: "はなしがすこしもどりますが、〔ないよう〕。",
      zh: "话题稍微回到刚才，〔内容〕。",
      scene: "回到之前的话题时",
      pattern: "転換・話が戻る",
      week: 3,
      fillIn: "〔内容〕",
    },
    {
      id: "p1-filler-009",
      category: "つなぎ言葉",
      priority: 2,
      ja: "〔テーマ〕についてはどうかというと、〔内容〕です。",
      kana: "〔てーま〕についてはどうかというと、〔ないよう〕です。",
      zh: "关于〔主题〕的话，是〔内容〕。",
      scene: "展开新话题时",
      pattern: "話題展開",
      week: 3,
      fillIn: "〔テーマ〕・〔内容〕",
    },
    {
      id: "p1-filler-010",
      category: "つなぎ言葉",
      priority: 2,
      ja: "別の言い方をすると、〔言い換え〕です。",
      kana: "べつのいいかたをすると、〔いいかえ〕です。",
      zh: "换句话说，是〔换一种表达〕。",
      scene: "重新表述刚才说的内容",
      pattern: "言い換え",
      week: 3,
      fillIn: "〔言い換え〕",
    },
    {
      id: "p1-filler-011",
      category: "つなぎ言葉",
      priority: 1,
      ja: "要は、〔まとめ〕ということです。",
      kana: "ようは、〔まとめ〕ということです。",
      zh: "总之，就是〔总结〕。",
      scene: "总结要点时",
      pattern: "まとめ・要は",
      week: 2,
      fillIn: "〔まとめ〕",
    },
    {
      id: "p1-filler-012",
      category: "つなぎ言葉",
      priority: 1,
      ja: "まとめると、〔結論〕ということになります。",
      kana: "まとめると、〔けつろん〕ということになります。",
      zh: "总结来说，就是〔结论〕。",
      scene: "对话结尾总结时",
      pattern: "まとめ・まとめると",
      week: 2,
      fillIn: "〔結論〕",
    },
    {
      id: "p1-filler-013",
      category: "つなぎ言葉",
      priority: 2,
      ja: "〔条件〕という点では、〔判断〕と言えるかもしれません。",
      kana: "〔じょうけん〕というてんでは、〔はんだん〕といえるかもしれません。",
      zh: "从〔条件〕这个角度来说，也许可以说是〔判断〕。",
      scene: "条件性给出意见时",
      pattern: "条件付き意見",
      week: 4,
      fillIn: "〔条件〕・〔判断〕",
    },
    {
      id: "p1-filler-014",
      category: "つなぎ言葉",
      priority: 2,
      ja: "〔前提〕という前提で言うと、〔内容〕です。",
      kana: "〔ぜんてい〕というぜんていでいうと、〔ないよう〕です。",
      zh: "以〔前提〕为前提的话，〔内容〕。",
      scene: "设定前提进行说明时",
      pattern: "前提・という前提で",
      week: 5,
      fillIn: "〔前提〕・〔内容〕",
    },
    {
      id: "p1-filler-015",
      category: "つなぎ言葉",
      priority: 2,
      ja: "以上が私の〔テーマ〕についての考えです。",
      kana: "いじょうがわたしの〔てーま〕についてのかんがえです。",
      zh: "以上是我对〔主题〕的想法。",
      scene: "结束一段发言时",
      pattern: "締め・以上が",
      week: 4,
      fillIn: "〔テーマ〕",
    },
  ];

  // ─────────────────────────────────────────────
  // エクスポート
  // ─────────────────────────────────────────────
  const allPhrases = [
    ...cat1_reaction,
    ...cat2_self,
    ...cat3_reason,
    ...cat4_request,
    ...cat5_emotion,
    ...cat6_filler,
  ];

  // 週別にグループ化したビュー
  const byWeek = {};
  allPhrases.forEach((p) => {
    const w = p.week || 1;
    if (!byWeek[w]) byWeek[w] = [];
    byWeek[w].push(p);
  });

  // カテゴリー別ビュー
  const byCategory = {};
  allPhrases.forEach((p) => {
    if (!byCategory[p.category]) byCategory[p.category] = [];
    byCategory[p.category].push(p);
  });

  return {
    allPhrases,       // 全100句
    byWeek,           // 週別
    byCategory,       // カテゴリー別
    cat1_reaction,    // カテゴリー1のみ
    cat2_self,        // カテゴリー2のみ
    cat3_reason,      // カテゴリー3のみ
    cat4_request,     // カテゴリー4のみ
    cat5_emotion,     // カテゴリー5のみ
    cat6_filler,      // カテゴリー6のみ
    totalCount: allPhrases.length,
  };
});
